language: node_js
node_js: 6.2.2

script:
  - npm run build
  - npm test

deploy:
  - provider: s3
    bucket: components.dashaudio.co
    region: eu-west-1
    acl: public_read
    local_dir: build/
    upload_dir: $(git describe --tags --always --dirty)
    skip_cleanup: true
    access_key_id:
      secure: I+r1jIHpA+mIm2mu0tXZ6O8md1ocCsU0ZV25L1lM8FycSd2jKrhCCFR+OIyKriEEEA3P3NmQpJfor3/0g/5TtCRPLmj++AuMivz46/MTVdEbsy8Wezc4sorXScfXadAUDUhYfGN4f2KpIk9Itb01uSsLZ9duP0Rlx4Rf6Flnb8SszPkhh9HAzZNDekMEy7yr6rDCG4Ritb5259oj1xUZp/EI1bc5kUndj0E+jk2E7frbFaXC506MOp5zdbwVWObgyEn4HTKFvC8ahRE+moWZLHULP1rnrzfI+IA9ysTkEvgu3Dcx9KwFhBLfLZ1wmVPrZMRsOsQV5QtkZSolGJq7Y1GahC8TJt4cDSXpVnkgh1zOI6I+bZzyxVbwjkOMDAHRRRuvZyuBTFMM3pWUXnt47T3OqqLGXusgxFk1q/kuk1firEOhHQpG2pMbf4QANocdIl08m7kiHIpxLsnVAseVq19H+pZRUeLrpQtu2B75qyC+v2mbFtSrQJ44yRBzXIYKyGhEq9Tk24UZm9WcD9W64j3ImNBOzw6FDJwQZmH+hKI3qgsd+PbDkPOu5KaeXlWn8JFgmqlHT3kiq6azpsRmviTNsGD0HwbP3/aajN3fVBIzQbqUfAPajZ99xqTua3iwJT27ubyo513wOWJG4Se+H5cwbxmBCo4mVj4S5NULc64=
    secret_access_key:
      secure: ZhKNOUxVLpVDgZWYr64P2jrtb32Du4a2F5549FzUruw1MvyQ+rjtxCsLZtKTgxqbT+jtzCPxZbKIPUOSKAhfCVKGb+M0NBp+ulIGz0m8UIY7LKz7MzT5+biJCgXA/WbpNWSIzKmfHwpciJGix0q/gn0PAJChf0p0verLrq7ipRAtq19u3NLMIFXruAp/RpEs2curRyktV4Jy0uBbv7NbnZTSKuFTMsISIXELgpMCYSBNs3AnFpkBXPrK3zrj3Gx/fGuc9yR04HnrhKFMPERBoMPBzGH2cQYEymw0uW5nU7oEbFaYxOek/NzClIl3FGOpgOA2Qa0Mpq5C7fMvK120EEAnIbZkEVNldK7EqB8AnQ9uPCcF99QWTQ09oo0+AGFFZ3XT2g3LACfLZ6dVS4cYuhHdxGLwjz4KN6WB2MYZZ8afHN7t/jPlGLOu699E6BnQr06pOK9vU6JnQ/dbyu4qF4eMT6Md/AkIWR68Ly7qrlCJxFOalb+OzOIZpnva4BG22z4rAKqjldAGtDIu3KnvXc+Ts2BSZZO/3QT27P4+p/FrmfPMyp5opSJpYouR+9N3vmsfj6jorZvznMFfNp3jgKRjMn7AvIrBh8WOAuQjH/J0IYxY1PLVbr3Y/q9A+yX8yIJ2bdilfPUELz/taFCWBxo9cCaHH9AOtCRn8GfeHsg=
  - provider: npm
    skip_cleanup: true
    email:
      secure: j6wirha3eb1YGGhrkXac39/DBkLL9qIovYCUue3HT2ABnISzTpxO6Bnc4L2D29P7hEHeFsCeM0wrI5C63v1YtKnEc1Gq2TrJS2qI6s8P5FQ6Lm6J2KgaBcR3KAAryEnJBq39o3Q34UEn0kuwnX/ZeOTxcxKo8fLlqzGeLO/w4ONcg3CXbpg0AqucLn8SKtL0PGBwlXD8NsMMP9cIgOlpQwTwDktGrsGHOFbxFAgi38zGcBnaaDja4fn9HByun8LItQCiu6Umm59Bxj6r094ZdpHpwgviwlcioRgaehjVNUi38DlZWQFpGjNG4rB6HGCxHJqdpnyE9GnYTfrDJDv6kEDH9x3B+aadsm2ItG/5AD85zO8rNcwYSmOhPEQlC8hzYsdR1F6AbcQGTR1qM9icDwhdamqCcSsHSMHKnN7iJOtsNDbg9UeBN5/J2PhwTiTKDxZVvDCYUOv12EO3ZkyJZzmDtQgvj7LCCndevV/doa7hEHzuPmvxuv1U9y9fnBFPiZ0COrO12A7cO/Fcg/I4TT0ib7tp52dSTPrwF5wBmtrFKlwgxaiPzEN8XR5rmSIkZy/XpNKp/o6tqXURMa4L8e9ZT4Z9DdQTtxe9lgAywWMFTWVm6o6dxdXnAiA+tj0GMssX3advWxNfefUbphEiiCv+ys2CRBdM313w5pd08Uk=
    api_key:
      secure: a2R8cCuKQPXpSly53ciB/H56zKjXaxc8epAdzuAYBXeLGd6y9leT8Se3n3aMPxBXPUT4pA5uRBWmTNBv3DcZHv44tRuXqN8VrPSgM4iz4Z0k3P8760qa9Oszk2yvMNq/LgoaTkmX0ovxF40yZ9ozf6F5xt/4dvIJ5saLbZ5UhiqTajKVw9hKewiETdevtUbRwQLaxyNzoxx6i/bRqonl8a60aKm6KplP2Vt1bsIKCiGQYAkgqLNvwp/i6pptZ5DEHmqAiOFzx8HKfcU5t2pLv6oxhv6x/0S3tTQDOYRFnPE+JEbHoBlgKSI+yujV36JP5QetBtNET33hUJxqNAQEolyNLLTdH/BjxS3sVkJ6wmOxNqiwXbJYnjjePlcr5AGzCCe1bTKiU+6vHV6w0/ClKxwvLokgDC6PEFJk/1397k4UkX8NDm8sLaT7n84oJSdBT37bX1+UK94czJ+8HJQ/ApfgmqFTQUUEg8mkD/JBWS0eOInZl5eigdgqH4DFsGdpfXBLlDZ2pagBlSqd7WoIl/18rqNPq6kew0g0/c1pgUTgFD4TpWYQl2HNw1WmcpyK9O9XFUYgX03KzSXfZenYa1htmmOn70Uups+3zV1VGZcWU15ngCSe9pJvb/5pxgto3wZlcD3BkEE8QGlt8/DWDrNdL1xZw2waRwUkzGlFPRQ=
    on:
      tags: true

notifications:
  email: false

env:
  global:
    - NODE_ENV=development
    - DASH_ASSETS_BASE="https://components.dashaudio.co/$(git describe --tags --always --dirty)"
