language: node_js
node_js: 6.3.0

script:
  - npm run build
  - npm test

-: &deploy-s3
  provider: s3
  bucket: dash-components
  region: eu-west-1
  acl: public_read
  local_dir: build/
  skip_cleanup: true
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_KEY_SECRET

deploy:
  - <<: *deploy-s3
    upload_dir: versions/$(npm info dash-components version)
    cache_control: public, max-age=315360000 # TODO: Set multiple values
    on: { tags: true }
  - <<: *deploy-s3
    upload_dir: production
    cache_control: public, max-age=3600 # TODO: Set multiple values
    on: { branch: production }
  - provider: npm
    skip_cleanup: true
    api_key: $NPM_KEY
    email: $NPM_EMAIL
    on: { tags: true }

notifications:
  email: false
  slack: $SLACK_KEY

env:
  global:
    - NODE_ENV=development
    - DASH_ASSETS_BASE="https://components.dashaudio.co/versions/$(npm info dash-components version)"
