language: node_js
node_js: 6.2.2

script:
  - npm run build
  - npm test

deploy:
  - provider: npm
    skip_cleanup: true
    email:
      secure: j6wirha3eb1YGGhrkXac39/DBkLL9qIovYCUue3HT2ABnISzTpxO6Bnc4L2D29P7hEHeFsCeM0wrI5C63v1YtKnEc1Gq2TrJS2qI6s8P5FQ6Lm6J2KgaBcR3KAAryEnJBq39o3Q34UEn0kuwnX/ZeOTxcxKo8fLlqzGeLO/w4ONcg3CXbpg0AqucLn8SKtL0PGBwlXD8NsMMP9cIgOlpQwTwDktGrsGHOFbxFAgi38zGcBnaaDja4fn9HByun8LItQCiu6Umm59Bxj6r094ZdpHpwgviwlcioRgaehjVNUi38DlZWQFpGjNG4rB6HGCxHJqdpnyE9GnYTfrDJDv6kEDH9x3B+aadsm2ItG/5AD85zO8rNcwYSmOhPEQlC8hzYsdR1F6AbcQGTR1qM9icDwhdamqCcSsHSMHKnN7iJOtsNDbg9UeBN5/J2PhwTiTKDxZVvDCYUOv12EO3ZkyJZzmDtQgvj7LCCndevV/doa7hEHzuPmvxuv1U9y9fnBFPiZ0COrO12A7cO/Fcg/I4TT0ib7tp52dSTPrwF5wBmtrFKlwgxaiPzEN8XR5rmSIkZy/XpNKp/o6tqXURMa4L8e9ZT4Z9DdQTtxe9lgAywWMFTWVm6o6dxdXnAiA+tj0GMssX3advWxNfefUbphEiiCv+ys2CRBdM313w5pd08Uk=
    api_key:
      secure: a2R8cCuKQPXpSly53ciB/H56zKjXaxc8epAdzuAYBXeLGd6y9leT8Se3n3aMPxBXPUT4pA5uRBWmTNBv3DcZHv44tRuXqN8VrPSgM4iz4Z0k3P8760qa9Oszk2yvMNq/LgoaTkmX0ovxF40yZ9ozf6F5xt/4dvIJ5saLbZ5UhiqTajKVw9hKewiETdevtUbRwQLaxyNzoxx6i/bRqonl8a60aKm6KplP2Vt1bsIKCiGQYAkgqLNvwp/i6pptZ5DEHmqAiOFzx8HKfcU5t2pLv6oxhv6x/0S3tTQDOYRFnPE+JEbHoBlgKSI+yujV36JP5QetBtNET33hUJxqNAQEolyNLLTdH/BjxS3sVkJ6wmOxNqiwXbJYnjjePlcr5AGzCCe1bTKiU+6vHV6w0/ClKxwvLokgDC6PEFJk/1397k4UkX8NDm8sLaT7n84oJSdBT37bX1+UK94czJ+8HJQ/ApfgmqFTQUUEg8mkD/JBWS0eOInZl5eigdgqH4DFsGdpfXBLlDZ2pagBlSqd7WoIl/18rqNPq6kew0g0/c1pgUTgFD4TpWYQl2HNw1WmcpyK9O9XFUYgX03KzSXfZenYa1htmmOn70Uups+3zV1VGZcWU15ngCSe9pJvb/5pxgto3wZlcD3BkEE8QGlt8/DWDrNdL1xZw2waRwUkzGlFPRQ=
    on:
      tags: true

notifications:
  email: false
